{% set name = "pyopenrivercam" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/localdevices/pyorc/archive/refs/tags/v{{ version }}.tar.gz
  sha256: cd289b09de03ecac75afa3cec8c18ad4d6d749766912618113ec6e1a2c78a3cc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:

  host:
    - python >=3.8
    - pip

  run:
    - python >=3.8
    - cartopy
    - dask
    - descartes
    - geojson
    - geopandas
    - geos
    - gitpython
    - matplotlib-base
    - netCDF4
    - numpy
    - opencv
    - openpiv
    - pip
    - pyproj
    - pytest
    - rasterio
    - scikit-image
    - scipy
    - shapely
    - tqdm
    - watermark
    - xarray

test:
  imports:
    - pyorc
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/localdevices/pyorc
  summary: Measure river and stream surface velocity and river flow from UAV, smartphone or IP camera videos
  description: |
    pyOpenRiverCam is an open-source API for estimating surface velocity and river flow from IP, drone or smartphone camera
    videos. It performs preprocessing, surface velocity estimation, spurious velocity filtering, cross section sampling, 
    infilling of missings, and integration to discharge. A user only needs to perform light field work and collect 
    videos. It is pure python code and therefore easy to take up in your own software project or perform research with or
    develop new features.
  license: AGPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  doc_url: https://localdevices.github.io/pyorc
  dev_url: https://github.com/localdevices/pyorc

extra:
  recipe-maintainers:
    - hcwinsemius
