{% set name = "pyopenrivercam" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/localdevices/pyorc/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 308eb95035bd472ba78c3be4913a1f36e88b01667c333ca2352faf57b0f6b76c

build:
  number: 0
  noarch: python
  entry_points:
    - pyorc = pyorc.cli.main:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python =3.11
    - flit
    - pip
  run:
    - python >=3.11
    - cartopy
    - click
    - dask
    - descartes # platform does not support 1.1.0 for some reason, but descartes works! therefore for now pip check is excluded
    - flox
    - ffpiv
    - geojson
    - geopandas
    - geos
    - gitpython
    - matplotlib-base
    - netCDF4
    - numba
    - numpy >=1.23, <2  # numba only works < 2.0
    - opencv
    - openpiv
    - pip
    - pyproj
    - pytest
    - pyyaml
    - rasterio
    - scikit-image
    - scipy
    - shapely
    - tqdm
    - typeguard
    - watermark
    - xarray
    - yaml
test:
  imports:
    - pyorc
    - pyorc.cli
  requires:
    - pip
  commands:
    # - pip check  # bring back pip check once descartes moves to >1.1.0
    - pyorc --help
about:
  home: https://github.com/localdevices/pyorc
  summary: Measure river and stream surface velocity and river flow from UAV, smartphone or IP camera videos
  description: |
    pyOpenRiverCam is an open-source API for estimating surface velocity and river flow from IP, drone or smartphone camera
    videos. It performs preprocessing, surface velocity estimation, spurious velocity filtering, cross section sampling, 
    infilling of missings, and integration to discharge. A user only needs to perform light field work and collect 
    videos. It is pure python code and therefore easy to take up in your own software project or perform research with or
    develop new features.
  license: AGPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  doc_url: https://localdevices.github.io/pyorc
  dev_url: https://github.com/localdevices/pyorc

extra:
  recipe-maintainers:
    - hcwinsemius
